### ISSUE TITLE
Replace "about" language on website

### ISSUE THREAD

**Issue by Nishaat** [DeltaInstitute/LuminDashboard#22]
Hey Dan, 

here's some updated language for our website, that reflects what's in the new partner toolkit and the new pilot design.

https://docs.google.com/a/delta-institute.org/document/d/1c0c1ym1-f7BT0F-VuHpCvegwxzkNfkQEa9JZLnrkXwc/edit?usp=sharing

**Comment by danswick** [comment]
Updated, but is there anything else we want to add now that the pilot is underway, @Nishaat ?
