### ISSUE TITLE
Add dashboard button and "underway" language to homepage

### ISSUE THREAD

**Issue by danswick** [DeltaInstitute/LuminDashboard#27]
Content on drive.

- [x] Dashboard button
- [ ] Underway language

**Comment by danswick** [comment]
@Nishaat, how do you feel about this language for the home page? We just want to say that the pilot has launched and we're no longer accepting applicants. 

> The Delta*Lumin* pilot is currently underway and we are no longer accepting applications. If you are interested in participating in future Delta*Lumin* programs, please reach out to <a href="mailto:hello@deltalumin.com?Subject=Future%20Pilot%20Interest" target="_top">hello@deltalumin.com</a>.

**Comment by Nishaat** [comment]
Through funding provided by the Illinois Science & Energy Innovation Foundation (ISEIF), Delta Institute has collaborated with IDEO to use human-centered design to develop a product that empowers consumers with useful information from their smart meters. The product is DeltaLumin.

The DeltaLumin pilot is currently underway and we are no longer accepting applications. If you are interested in participating in future DeltaLumin programs, please reach out to hello@deltalumin.com<mailto:hello@deltalumin.com>.

**Comment by danswick** [comment]
Thanks, @Nishaat! Added new language in b459fd513c628f6a0f7dcf09ab591e8d695d0063 

:bee: :bear: :beetle:
