### ISSUE TITLE
Add partner logos to footer

### ISSUE THREAD

**Issue by danswick** [DeltaInstitute/LuminDashboard#3]
IDEO - still waiting for confirmation 

ISEIF - ready to go. Saved on [Drive](https://drive.google.com/a/delta-institute.org/folderview?id=0BxBgtZTXpybDUUozMHRpTVVvZ3M&usp=sharing).

**Comment by vrroanhorse** [comment]
IDEO logo ready: https://drive.google.com/a/delta-institute.org/file/d/0BxBgtZTXpybDc1Y5dUxrcUhnWVE/view?usp=sharing

**Comment by danswick** [comment]
YES! Thanks, @colleenmcginnis and @vrroanhorse :fried_shrimp: :flags: :camel:
