### ISSUE TITLE
Calendar with 6 rows doesn't fit in view box

### ISSUE THREAD

**Issue by danswick** [DeltaInstitute/LuminDashboard#48]
Options: 

- [ ] Change height of view box
- [ ] Set view box height as function of number of calendar rows 
- [ ] Flip speech bubble around for top row of 6-rowed charts

**Comment by colleenmcginnis** [comment]
the bubble is cut off this week! :speech_balloon:

**Comment by danswick** [comment]
Fixed in a7311cb80cd52dbf46aad6665d873491d780ef56 :scissors: :speech_balloon:
