### ISSUE TITLE
Update colors of donut slices?

### ISSUE THREAD

**Issue by colleenmcginnis** [DeltaInstitute/LuminDashboard#54]
@danswick I updated all the icons to be the same size and chose unique colors for each, listed here: https://gist.github.com/colleenmcginnis/2d799f6259b1655688a4 Let me know if I can do anything else!

**Comment by danswick** [comment]
Awesome, thank you! i don't think we'll be able to reignite the donut chart fires for a few days at least, but let's true this up with #42 when we pick it back up. 

Also, protip, if you rename the 'updated icons' text file in your Gist to updated_icons.md, GH will render it as a nice HTML table! https://gist.github.com/danswick/ead472841f8d0c150b90 

:cat2: :ox: :bug:

**Comment by danswick** [comment]
Actually, even more pro would be just pasting that sweet table right here! 

|          icons           |     **Model**      |  baseline survey   |       color      |
|--------------------------|--------------------|--------------------|------------------|
| ac.svg, ac.png           | AC                 | centeral or window | #6ab1b9          |
| N/A                      | ~~Clothes Dryer~~  |                    | N/A              |
| N/A                      | ~~Clothes Washer~~ |                    | N/A              |
| N/A                      | ~~Computer~~       |                    | N/A              |
| dishwasher (in folder)   | dishwasher         |                    | #00a8ab          |
| freezer.svg, freezer.png | Freezer            |                    | #98bdce          |
| heater.svg, heater.png   | Heating System     | Type of heating    | #c25700          |
| spaceheater.svg, "".png  | Space Heater       |                    | #d78d2a          |
| light.svg, light.png     | lighting           | inc, CFL, LED      | #d88d2a          |
| plug.svg, plug.png       | everything else    |                    | #787878          |
| N/A                      | ~~Pool~~           |                    | N/A              |
| refrigerator.svg, "".png | refrigerator       |                    | #0071ad          |
| range.svg, range.png     | range              | stove (elec)       | #885928          |
| tv.svg, tv.png           | TV                 |                    | #457878          |
| N/A                      |                    |                    | N/A              |

**Comment by colleenmcginnis** [comment]
oooo thanks! im still a gh novice :baby:

**Comment by danswick** [comment]
Colors updated and donut chart swapped for long john chart as per e2b26182863678a27ea962905b58cd39fa970486
