### ISSUE TITLE
Incomplete Historical Data

### ISSUE THREAD

**Issue by MartinCoozyBrown** [DeltaInstitute/LuminDashboard#56]
A few participant do not have a complete 2 years of historic data. Can’t calculate bill forcast without at least 1 year (can’t divide by zero). Participants with this issue: 51, 70, 74.
Proposed solution- find participants with similar appliances and usage patterns and apply their data to fill in the gaps.

**Comment by danswick** [comment]
I think that's a good solution. A projection of a projection. :flashlight: :flashlight: 

Do you want to work together on that or do you think you could just run with it?

**Comment by MartinCoozyBrown** [comment]
I can do this next week. projections of projections, slopes of slopes, WE ARE OUT OF CONTROLL!
