### ISSUE TITLE
"spentmonth" not calculating for #66

### ISSUE THREAD

**Issue by MartinCoozyBrown** [DeltaInstitute/LuminDashboard#57]
spentmonth for participant 66 is not calculating. Cell say N/A, Error message reads “no matches are found in filter". What this? 

When I tried entering there participant id into dashboard, i didn’t get error message but the page never loaded either.

**Comment by danswick** [comment]
Fixed. Sometimes, sheets doesn't correctly update cell references when you duplicate a sheet. You can fix it by either: 

1. Double-clicking into each sheet, then hitting enter for each cell with an error
2. Doing the above, then just dragging that cell down through the range with problems

This theoretically shouldn't happen again, but good to watch for if we add any new user sheets.
