### ISSUE TITLE
RSVP link for workshop

### ISSUE THREAD

**Issue by Nishaat** [DeltaInstitute/LuminDashboard#62]
Hey Dan, 

The Google RSVP form is up and ready to be added to the website. 
https://docs.google.com/forms/d/1W3YHdHEftCka1UON543mE8hTucGu6uiMHXHytPaC8Gk/viewform 

everything else for the event can be found here: https://docs.google.com/a/delta-institute.org/document/d/1ZB0o8yP6X4QX4b_2jWh0pviEYooqfB8Xm05hsqtMUcA/edit?usp=sharing 

thanks!
nishaat

**Comment by danswick** [comment]
Done as of 0e8bc6d7e88a7790b0d010c51c9ded12e80d6a97
