### ISSUE TITLE
Naming files

### ISSUE THREAD

**Issue by colleenmcginnis** [DeltaInstitute/LuminDashboard#63]
Let’s do this: 

/ID#_ChartID_Month#_Email#.png

So this week we should have these four files: 

Spending Forecast: 	/ID#_SF_1_1.png
Appliance Diagnosis: 	/ID#_AD_1_1.png
Monthly Use:			/ID#_MU_1_1.png
Weekly Use:			/ID#_WU_1_1.png

Sound ok? 

--
For reference: 

Chart ID:
Spending Forecast (calendar) = SF
Appliance Diagnosis (bar chart) = AD
Monthly Use = MU
Weekly Use = WU 
Goal Setting = GS 
Program Match TBD?

Month#_Email#: 
May 15: 1_1
May 31: 1_2
June 15: 2_1
June 30: 2_2
July 15: 3_1
July 31: 3_2

**Comment by Nishaat** [comment]
Looks good to me!

**Comment by danswick** [comment]
Done as of bbeaa979670080204bfb3e308577302680c1ba22
