### ISSUE TITLE
'download image' button appears in user's emails

### ISSUE THREAD

**Issue by Nishaat** [DeltaInstitute/LuminDashboard#77]
Hey Dan, 

I saw in a participant's email that a download/down arrow thing shows up when you hover over an image in the mid-month email from June. IDK if it's an actual problem, or an indicator of another problem, or if it simply doesn't matter. But you're not here, so I can't ask you to your face. So here is this issue. 

Best,
Nishaat

**Comment by danswick** [comment]
@Nishaat, did it look like this? 

![image](https://cloud.githubusercontent.com/assets/2365503/8318483/7854c994-19ca-11e5-96c0-9d27db79faa0.png)

If so, that's just how gmail works (and possibly other email providers?) whenever there's an image in an email.
