### ISSUE TITLE
Vivian Dorado's got a fridge

### ISSUE THREAD

**Issue by Nishaat** [DeltaInstitute/LuminDashboard#78]
Vivian Dorado emailed the Hello email account and said her fridge is not in her Diagnosis that was mailed to her. She said she also mentioned this during the workshop, and it did not show up in her mailer. I emailed her and said we'd look into it. IDK if this goes here, or SF, but this felt right.

**Comment by colleenmcginnis** [comment]
@MartinCoozyBrown is adding an appliance easy to do? it would be awesome if we could fix this before i download all the charts tomorrow, but if not no worries!! maybe we can figure it out before the workshop?
