### ISSUE TITLE
Apps Calc Sheet is doing really weird things

### ISSUE THREAD

**Issue by MartinCoozyBrown** [DeltaInstitute/LuminDashboard#80]
The app calcs are getting pretty funky. For some reason, the appliances are not being multiplied by there quantity but just the quantity of appliance 1.

EX) user 67 on appCalc tab in calcAndLookups-  Appliance 2 (refrigerator) total usage in appliance spending diagnosis should be multiplied by the # of refrigerators, which is 1. instead it is being multiplied by  57.2, which is the number of light bulbs that user has. 

Where things are going wrong is in the 3rd part of the equation:

Part 1. Average KWH- 

=(VLOOKUP($G68,applianceDefaults!$A:$P,12,FALSE)) = 42- this is right

X

Part 2. Occupancy Multiplier- 

=if(vlookup($G68, applianceDefaults!$A:$P, 7, FALSE) = "yes", if(VLOOKUP($A68, participantData!$A:$B, 2, FALSE) < 2, applianceMultipliers!$F$2 ,if(VLOOKUP($A68, participantData!$A:$B, 2, FALSE) < 4, applianceMultipliers!$F$3, applianceMultipliers!$F$4)), 1)= 1- This is right too

X

Part 3. # of said appliance

=(VLOOKUP($A68, participantData!$A:$P, 7, FALSE))= 57.2 , EHHH, WRONG DUMBASS! it should be 1, because this user only has 1 fridge. BUT the user does have 57 light bulbs for some reason it is pulling this number.

I think what is missing is some logic is this last part of the equation but am not sure what yet. Ideas?

**Comment by MartinCoozyBrown** [comment]
Problem solved, Replaced part 3 of equation with IF statement

IF Appliance name= x appliance, than multiply by the # of said appliances that user has

ex for user 10 appliance 4 (fridge) 
=If("appliance4Name="Refridgerator-Freezer 22 cu ft-side by side ENERGY STAR", "app4NumAdjust"


Full correct equation for adjustedKWH for example above

=(VLOOKUP($Q11,applianceDefaults!$A:$P,12,FALSE))    *    if(vlookup($Q11, applianceDefaults!$A:$P, 7, FALSE) = "yes", if(VLOOKUP($A11, participantData!$A:$B, 2, FALSE) < 2, applianceMultipliers!$F$2 ,if(VLOOKUP($A11, participantData!$A:$B, 2, FALSE) < 4, applianceMultipliers!$F$3, applianceMultipliers!$F$4)), 1)    *   if(Q:Q=Q11,T11)

Link to sheet:

https://docs.google.com/spreadsheets/d/18IPeu-Ps83XukfXeOuBew-7DWiIC1Y39u3N95dPtaEg/edit#gid=313313192

**Comment by colleenmcginnis** [comment]
:clap: :tada: 
:dragon: is back
