### ISSUE TITLE
Appliance Diagnosis - Time Period

### ISSUE THREAD

**Issue by kbdick** [DeltaInstitute/LuminDashboard#83]
It's not clear what time period the appliance diagnosis covers. Is it over a day, week, or month. Perhaps it should say "See what you are spending every TIME PERIOD on your appliances and electronics."

**Comment by colleenmcginnis** [comment]
@kbdick We actually talked about that this morning. It's cumulative for the month. How about "See how much we think you have spent on your appliance and electronics so far this month"?

**Comment by MartinCoozyBrown** [comment]
@colleenmcginnis sound good to me. Can we make the "think" in bold size 72 font?

**Comment by colleenmcginnis** [comment]
:&
