### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Nishaat** [DeltaInstitute/LuminDashboard#9]
HEY DAN!

I have maneuvered myself onto GitHub, a world I find intimidating. 

Can you please set up Google Analytics on the landing page? I'd like to peek into our web traffic. 

THANKS
Nishaat

**Comment by danswick** [comment]
Added via a098c39e8b4cc882c6dd81d3e018748342ea36bf and 438418ece89bf851f46ae23efad7c757e5ea947b! 

Just set it up, so it might take a little while to start working. Feel free to reopen this issue if you find that the data isn't flowing within a couple of days.

**Comment by Nishaat** [comment]
Thanks Dan. Do you know how I get access to the DeltaLumin Analytics page? I didn't see it in the hello@delta-institute.org account, and it's not showing up in my own delta account.

**Comment by danswick** [comment]
All set for both accounts!
